name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build the Docker image (amd64)
      run: docker buildx build --platform linux/amd64 --file Dockerfile --tag ciudse-telemetry-amd64 .
      
    - name: Build the Docker image (arm64)
      run: docker buildx build --platform linux/arm64 --file Dockerfile --tag ciudse-telemetry-arm64 .
      
    - name: Save the Docker image and compress (amd64)
      run: docker save ciudse-telemetry-amd64 | gzip > ciudse-telemetry-amd64.tar.gz
      
    - name: Save the Docker image and compress (arm64)
      run: docker save ciudse-telemetry-arm64 | gzip > ciudse-telemetry-arm64.tar.gz
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload Release Assets (Docker image amd64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./
        asset_name: ciudse-telemetry-amd64.tar.gz
        asset_content_type: application/gzip
        
    - name: Upload Release Assets (Docker image arm64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./
        asset_name: ciudse-telemetry-arm64.tar.gz
        asset_content_type: application/gzip
